### ISSUE TITLE
Issue with Docker Image upgrade from 5.3.7 to 5.3.8 pertaining to the Lavarel.log file

### ISSUE THREAD

**Issue by ShadowPeo** [grokability/snipe-it#10626]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Upon upgrading from docker 5.3.7 to 5.3.8 or latest there is an error related to the Laravel.log file ("UnexpectedValueException  : The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied") downgrading back to 5.3.7 fixes the issue with no noticeable consequence.

The error exists in the logs prior to any access to the web interface and utilizing the web interface may generate another similar error. The web interface itself simply comes back with a 500 error

There is no volume for the log file/folder so its not a file system permissions issue

### Reproduction steps

1. Working install on 5.3.7
2. Upgrade to 5.3.8 via editing the docker-compose file
3. Pull the docker image, put up the contailer
4. Error exists in logs prior to even logging in

### Expected behavior

Boot of image without the error and ability to access the interface

### Snipe-IT Version

5.3.8

### Operating System

Ubuntu

### Web Server

Official Docker Image Version

### PHP Version

Official Docker Image Version

### Operating System

Windows 10 21H2

### Browser

Edge (chromimum), Chrome, Firefox

**Comment by ShadowPeo** [comment]
![Snipe Error - Prior to web interface access attempt](https://user-images.githubusercontent.com/7752044/152900779-cc00ad4e-c7dc-4258-a296-0fe7bd6fca78.png)
![Snipe Error - After to web interface access attempt](https://user-images.githubusercontent.com/7752044/152900785-a4647586-2d65-494b-ada9-fd7f613c7c91.png)

**Comment by uberbrady** [comment]
The only big change from 5.3.7 to 5.3.8 that we've seen affecting Docker users is `APP_ALLOW_INSECURE_HOSTS` - basically, make sure your `APP_URL` in your Environment is actually correct (matching what you see in your URL bar), or if you can't do that, and are in a safe enough environment, set `APP_ALLOW_INSECURE_HOSTS` to `true`.

If it's not that, I can't imagine what could be changing in terms of permissions?

**Comment by ShadowPeo** [comment]
@uberbrady Yup that got it, but it does not explain why I was getting the above error on the Lavarel logs, especially considering they are internal to the docker image

**Comment by uberbrady** [comment]
Glad that at least got the problem - but, you're right, it does not at all explain *why* you got that error in the laravel logs. Very very weird! Could it be from when the image was built? Maybe some initial composer run? I don't know.

**Comment by ShadowPeo** [comment]
It also happens on the latest tag which was built only a few hours ago

**Comment by JonathonReinhart** [comment]
I confirmed that `/var/www/html/storage/logs/` is empty in the v5.3.8 image.

I *think* the problem might be that [these `artisan` invocations](https://github.com/snipe/snipe-it/blob/v5.3.8/docker/startup.sh#L63-L65) in `startup.sh` run *as `root`*, which might create the log file owned as `root`. Then, Laravel running as the webserver user might be subsequently unable to open the log file.

I *just* encountered this while setting up a new instance for testing, using this `docker-compose.yml`:
```yaml
version: '2'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: userpassword1

  snipeit:
    image: snipe/snipe-it:v5.3.8
    links:
      - db
    volumes:
      - ./data/snipeit:/var/lib/snipeit

    ports:
      - "127.0.0.1:8888:80"

    environment:
      APP_URL: "http://127.0.0.1:8888/"
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_PORT_3306_TCP_PORT: 3306    # https://github.com/snipe/snipe-it/issues/6578

      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: userpassword1
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

      # Uncomment these for debugging
      APP_DEBUG: 1
      APP_LOG_LEVEL: debug
```

The problem is that mysql is not ready by the time the startup script goes to run the migrations, so they fail and write to the log.
