### ISSUE TITLE
Pre-Flight URL check fails due to "/setup" in path

### ISSUE THREAD

**Issue by koelle25** [grokability/snipe-it#11800]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm just setting up a fresh instance of Snipe-IT 6.0.10 (on Docker using docker-compose).

The Pre-Flight URL check says:
> Uh oh! Snipe-IT thinks your URL is https://assets.test.xxx:443, but your real URL is https://assets.test.xxx/setup Please update your APP_URL settings in your .env file 

In my .env file `APP_URL` is set to `https://assets.test.xxx` (exactly).

Actually I can continue the wizard despite this error/warning.

### Reproduction steps

1. Create `docker-compose.yml` file (see below)
2. Start the Database container ( `docker-compose up -d db`) and wait for it being ready (`docker-compose logs -f db`)
3. Run the Snipe-IT container once to generate an `APP_KEY` (`docker-compose run snipeit`)
4. Add the generated `APP_KEY` to the `my_env_file`
6. Fire up the compose stack in "normal" mode (`docker-compose up -d`)
7. Navigate to the service in the browser, see the error/warning in pre-flight

<details>
<summary>docker-compose.yml</summary>
<p>

```yaml
version: '3.7'                                                                                                                                                                                                                          
                                                                                                                                                                                                                                        
services:                                                                                                                                                                                                                               
  snipeit:                                                                                                                                                                                                                              
    image: snipe/snipe-it:v6.0.10
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - my_env_file
    ports:
      - 80:80
      - 443:443
    volumes:
      - app:/var/lib/snipeit
      - ./cert.crt:/var/lib/snipeit/ssl/snipeit-ssl.crt
      - ./cert.key:/var/lib/snipeit/ssl/snipeit-ssl.key

  db:
    image: mariadb:10.9
    env_file:
      - my_env_file
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - db:/var/lib/mysql

volumes:
  app:
  db:
```

</p>
</details>

### Expected behavior

The `/setup` part should be ignored from the pre-flight check.

### Screenshots

![2022-09-08_14-39](https://user-images.githubusercontent.com/915514/189124070-d676acc3-dcb7-4fa5-b13a-7903e907fb64.png)


### Snipe-IT Version

6.0.10

### Operating System

Ubuntu 20.04.5 (Host & Container)

### Web Server

Apache 2.4.41 (Container)

### PHP Version

7.4.3 (Container)

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Device

_No response_

### Operating System

_No response_

### Browser

_No response_

### Version

_No response_

### Error messages

_No response_

### Additional context

_No response_
