### ISSUE TITLE
[Feature Request]: Asset API response includes parent location

### ISSUE THREAD

**Issue by RomanKlinghammer** [grokability/snipe-it#11897]
### Is your feature request related to a problem? Please describe.
So, I am making my own frontend asset inventory right now.
I have 4 main locations and every location got some rooms as child_locations in Snipe-IT.

My goal is to make a search where you can enter the main location as an filter and all the assets of the child_locations will be given.

Right now, when requesting an asset over the API, you only see the current location (Name + id) regardless whether it is a child_location or a parent_location.

![image](https://user-images.githubusercontent.com/95723118/193236409-4a3ad8bf-ba13-451a-9d66-c725c6eb0b8a.png)

### Describe the solution you'd like

Include the direct parent location in the API-getAsset response!

```
// API response from asset in child_location
 rtd_location:
             id: 23
             name: "ChildName"
             parent_loc: 
                     id: 1
                     name: "ParentName"


```
