### ISSUE TITLE
[Feature Request]: Jwt authentication

### ISSUE THREAD

**Issue by aardbol** [grokability/snipe-it#13307]
### Is your feature request related to a problem? Please describe.

Running snipe-it behind a reverse proxy such as Teleport that can pass a Jwt would be useful to take away the extra authentication layer in between. 

### Describe the solution you'd like

By relying on a Jwt, snipe-it could be authenticated with automatically and could get RBAC details from that token. Teleport is a living example that can pass such a token, which is also [supported by grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/jwt/).

### Describe alternatives you've considered

Google Oauth, but then there's two auth layers: first Oauth with teleport, then again with Snipe-it

**Comment by snipe** [comment]
I'm not sure of the ask here? The Snipe-IT API uses JWT already

**Comment by aardbol** [comment]
I couldn't find any documentation about that, but to clarify, this is about UI authentication primarily (but not exclusively). If Snipe-IT would listen to a Jwt token that's passed via the Request Headers, no manual authentication would be needed. Together with auto signup functionality and RBAC config, that would work ideally.

e.g. this is how to configure it in Grafana:
```
    auth.jwt:
      enabled: true
      disable_login_form: true
      header_name: Teleport-Jwt-Assertion
      email_claim: sub
      username_claim: sub
      auto_sign_up: true
      jwk_set_url: https://myteleport.instance:443/.well-known/jwks.json
      role_attribute_path: contains(roles[*], 'grafana-admin') && 'Admin' || contains(roles[*], 'grafana-editor') && 'Editor' || 'Viewer'
```
