### ISSUE TITLE
Api-Token gets invalidated when Restarting Client-Application

### ISSUE THREAD

**Issue by spammads** [grokability/snipe-it#13684]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Thanks for the great app. I create a Api-Token. It works unless I restart my client app. Then I get the response, that this token is no longer valid. Seems there is some kind of fingerprinting active!? 

### Reproduction steps

1. Create Api Token under User-Settings
2. Authenticate via Bearer Token
3. Restart Client-App
4. Bearer Token is not valid anymore

### Expected behavior

Api Token should be valid for 20 years as described in the documentation.

### Snipe-IT Version

6.3.0

### Operating System

Talos 1.5.2

### Web Server

Apache (Dockerfile)

### PHP Version

8.1.0

**Comment by spammads** [comment]
Btw: I set Api-Throttling to 5000 via Env-Vars. But this does not resolve this issue.

**Comment by snipe** [comment]
> Btw: I set Api-Throttling to 5000 via Env-Vars. But this does not resolve this issue.

API throttling wouldn't matter here - that just handles how many requests per minute/hour will be permitted before throwing a "too many requests" response.

Can you re-clarify the version of Snipe-IT you're using please. You stated 6.3.0, but that version doesn't exist.

**Comment by spammads** [comment]
Ah. Sorry. I misread. Its `6.2.0`.

**Comment by spammads** [comment]
First I got the impression that this occurs when the client-app is restarted. But now it occurs when the Snipe-It-Container is restarted (I use docker). Though I can see the Token is persisted between restarts it appears to not be valid anymore.

**Comment by BenGig** [comment]
Can confirm the behavior. We run it on Kubernetes, whenever the pods gets restarted the tokens get invalid. 

We fixed it by using a persistent volume mounted over `/var/lib/snipeit`. As long as the keys aren't stored in the persistent storage (database), this is the only way for Docker containers, as everything stored inside is ephemeral. Maybe you can add it to the documentation for Docker setups.

**Comment by dem972** [comment]
Hey ,
Looks like I'm facing the same issue, the pod can be moved to another node or restarting.
Then Im loosing the access and got 401 with api.
Mounting will not really help for me since the pod moving node, was thinking if there is a wey to force api token or store it on s3.

**Comment by mlerman-stratuscent** [comment]
I am experiencing same issue in version: `v7.1.15 build 16052 (g25bfd3e84)`
Am I doing something wrong during deployment?
Can you help point where to look?

**Comment by BenGig** [comment]
This is an excerpt of our Kubernetes configuration. On `/var/lib/snipeit`, we mount a persistent volume. The volume may not be of type `emptyDir` if your cluster has more than one node; NFS works fine. The oauth had been fetched from a classic installation we ran during evaluation. Deploying the oauth keys ensures valid API keys, wherever we deploy:
```
        volumeMounts:
        - mountPath: /var/lib/snipeit
          name: var-lib-snipeit-pv
        - mountPath: /var/www/html/storage/oauth-private.key
          name: var-lib-snipeit-oauth
          subPath: oauth-private.key
        - mountPath: /var/www/html/storage/oauth-public.key
          name: var-lib-snipeit-oauth
          subPath: oauth-public.key
        - mountPath: /var/test/oauth-public.key
          name: var-lib-snipeit-oauth
          subPath: oauth-public.key
      volumes:
      - name: var-lib-snipeit-pv
        persistentVolumeClaim:
          claimName: var-lib-snipeit-claim
      - name: var-lib-snipeit-oauth
        secret:
          items:
          - key: oauth-pubkey
            path: oauth-public.key
          - key: oauth-privkey
            path: oauth-private.key
          secretName: oauth-keys
```
