### ISSUE TITLE
Pre-Flight page does not support https

### ISSUE THREAD

**Issue by colinmollenhour** [grokability/snipe-it#14699]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

My `APP_URL` is an https url, and the page can be loaded with this url, but the Pre-Flight page seems to only support http.. 

Not sure if it's related, but upon submitting the Create a User page *there are no errors logged no error message returned*, it just redirects back to the same Create a User page no matter what I do it seems.. Been trying for hours!! Checked file permissions, COOKIE_DOMAIN, etc.

I'm completely stuck but will leave this running. It's live here if you want to see: http://snipeit-gwcws80-195420024406.apps.shipstream.io/setup

### Reproduction steps

Deploy to an https environment with APP_URL=https://....

### Expected behavior

Pre-Flight setup page loads properly with JS, CSS, links, form actions all using the https url.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/38738/7947eede-e160-4ecd-a7f9-dd3e3246bd2c)
![image](https://github.com/snipe/snipe-it/assets/38738/8efe2d53-b9ed-4768-9ca0-9326154b13d3)

### Snipe-IT Version

v6.4.0

### Operating System

Ubuntu (official Docker image)

### Web Server

Apache

### PHP Version

8.1.2

### Error messages

```shell
No errors!
```

### Additional context

Using Coolify 4.0.0 which just runs docker compose. Here is the file generated:

```
version: '3.8'
services:
    snipeit:
        image: 'snipe/snipe-it:v6.4.0'
        environment:
            - SERVICE_FQDN_SNIPEIT
            - APP_ENV=production
            - APP_DEBUG=true
            - 'APP_KEY=${APP_KEY}'
            - APP_URL=$SERVICE_FQDN_SNIPEIT
            - APP_TIMEZONE=America/Monterrey
            - APP_LOCALE=en-US
            - APP_TRUSTED_PROXIES=172.19.0.0/16
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=snipeit
            - DB_USERNAME=$SERVICE_USER_MYSQL
            - DB_PASSWORD=$SERVICE_PASSWORD_MYSQL
            - "DB_DUMP_PATH='/usr/bin'"
            - IMAGE_LIB=gd
            - SESSION_LIFETIME=86400
            - EXPIRE_ON_CLOSE=false
            - ENCRYPT=false
            - COOKIE_NAME=snipeit_session
            - COOKIE_DOMAIN=$SERVICE_URL_SNIPEIT
            - SECURE_COOKIES=true
            - CACHE_DRIVER=file
            - SESSION_DRIVER=file
            - QUEUE_DRIVER=sync
            - 'LOG_LEVEL=${LOG_LEVEL:-debug}'
        depends_on:
            - mariadb
        volumes:
            - 'data:/var/lib/snipeit'
            - 'logs:/var/www/html/storage/logs'
            - '/data/coolify/applications/gwcws80/.env:/var/www/html/.env'
        healthcheck:
            test:
                - CMD
                - /bin/true
            interval: 5s
            timeout: 20s
            retries: 10
        networks:
            gwcws80: null
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-ucwwwwk.entryPoints=http
            - 'traefik.http.routers.http-0-ucwwwwk.rule=Host(`snipeit-gwcws80-195420024406.apps.shipstream.io`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-ucwwwwk.entryPoints=https
            - traefik.http.routers.https-0-ucwwwwk.middlewares=gzip
            - 'traefik.http.routers.https-0-ucwwwwk.rule=Host(`snipeit-gwcws80-195420024406.apps.shipstream.io`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-ucwwwwk.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-ucwwwwk.tls=true
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://snipeit-gwcws80-195420024406.apps.shipstream.io'
            - caddy_ingress_network=gwcws80
            - coolify.managed=true
            - coolify.version=4.0.0-beta.276
            - coolify.applicationId=3
            - coolify.type=application
            - coolify.name=snipeit-gwcws80
            - coolify.pullRequestId=0
        restart: unless-stopped
        container_name: snipeit-gwcws80
    mariadb:
        image: 'mariadb:10.6-focal'
        volumes:
            - 'db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
            - MYSQL_DATABASE=snipeit
            - MYSQL_USER=$SERVICE_USER_MYSQL
            - MYSQL_PASSWORD=$SERVICE_PASSWORD_MYSQL
        networks:
            gwcws80: null
        labels:
            - coolify.managed=true
            - coolify.version=4.0.0-beta.276
            - coolify.applicationId=3
            - coolify.type=application
            - coolify.name=mariadb-gwcws80
            - coolify.pullRequestId=0
        restart: unless-stopped
        container_name: mariadb-gwcws80
volumes:
    data:
        name: data
    logs:
        name: logs
    db:
        name: db
networks:
    gwcws80:
        name: gwcws80
        external: true
```

Here is `env | sort` in the running container:

```
APP_DEBUG=true
APP_ENV=production
APP_KEY=base64:***REDACTED***
APP_LOCALE=en-US
APP_TIMEZONE=America/Monterrey
APP_TRUSTED_PROXIES=172.19.0.0/16
APP_URL=https://snipeit-gwcws80-195420024406.apps.shipstream.io
CACHE_DRIVER=file
COOKIE_DOMAIN=snipeit-gwcws80.apps.shipstream.io
COOKIE_NAME=snipeit_session
DB_CONNECTION=mysql
DB_DATABASE=snipeit
DB_DUMP_PATH='/usr/bin'
DB_HOST=mariadb
DB_PASSWORD=***REDACTED***
DB_PORT=3306
DB_USERNAME=***REDACTED***
ENCRYPT=false
EXPIRE_ON_CLOSE=false
HOME=/root
HOSTNAME=ece429a79da7
IMAGE_LIB=gd
LOG_LEVEL=debug
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
QUEUE_DRIVER=sync
SECURE_COOKIES=true
SERVICE_FQDN_SNIPEIT=https://snipeit-gwcws80-195420024406.apps.shipstream.io
SESSION_DRIVER=file
SESSION_LIFETIME=86400
TERM=xterm
```

Routing is done by Traefik.
