### ISSUE TITLE
[Docker] debug log file missing

### ISSUE THREAD

**Issue by Kofl** [grokability/snipe-it#14911]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Unable to get the debug log laravel.log to debug SAML login issue ""There was a problem while trying to log you in, please try again.

### Reproduction steps

Setup docker image and spin it up, following default config:

compose.yml

```
services:
  app:
    image: snipe/snipe-it:${APP_VERSION:-v7.0.4}
    restart: always
    volumes:
      - ./snipeit:/var/lib/snipeit
    ports:
      - "${APP_PORT:-8000}:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mariadb:10.6.4-focal
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 1s
      retries: 5
```

.env includes

`LOG_LEVEL=debug
LOG_CHANNEL=stderr
APP_DEBUG=true`

### Expected behavior

Log file in the container at the location: /var/www/html/storage/logs

_find / -name laravel.log_
does not locate it anywhere in the container

### Snipe-IT Version

7.0.4

### Operating System

Ubuntu

### Web Server

Docker Image

### PHP Version

Docker Image
