### ISSUE TITLE
Powershell user API - Can't add a user if there are special characters (é, à, ê, etc)

### ISSUE THREAD

**Issue by Doneven2012** [grokability/snipe-it#15310]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm using the API over Powershell (Both in Powershell directly and Powershell ISE) to create new users in SnipeIT and everything works pretty well unless I need to add a user where the first or last name has a special character. It seems like this works perfectly well on the snipeIT API explorer, but I can't get it to work. 

I tried with powershell variables at first (which works perfectly well if there are no special characters), then I tried removing them and hardcoding the values instead, but no difference.

### Reproduction steps

# API Explorer
Trying this query on the [API explorer](https://snipe-it.readme.io/reference/users-2), everything works as expected (obviously after running the initial commands to build the request headers)

```powershell
$response = Invoke-WebRequest -Uri 'https://develop.snipeitapp.com/api/v1/users' -Method POST -Headers $headers -ContentType 'application/json' -Body '{"groups":null,"vip":false,"first_name":"Mérie","last_name":"Fontaine","username":"mfontaine","password":"PotatoPotato102!","password_confirmation":"PotatoPotato102!","email":"merfontaine@example.com","jobtitle":"This is her title"}'
```

# My own SnipeIT instance
1. Fill the headers as usual with my API user/key
2. Run the following query 
2.1. 
```powershell
Invoke-WebRequest -Uri 'https://snipeit.mycompany.com/api/v1/users' -Method POST -Headers $headers -ContentType 'application/json' -Body '{"groups":null,"vip":false,"first_name":"Mérie","last_name":"Fontaine","username":"merfontaine","password":"PotatoPotato102!","password_confirmation":"PotatoPotato102!","email":"merfontaine@example.com","jobtitle":"This is her title"}'
```
3. I get the following output
```yml
StatusCode        : 200
StatusDescription : OK
Content           : {"status":"error","messages":{"first_name":["The first name field is required."],"username":["The username field is required unless ldap import is in 1."],"password":["The 
                    password field is required."...
RawContent        : HTTP/1.1 200 OK
Feature-Policy: accelerometer 'none';autoplay 'none';camera 'none';display-capture 'none';document-domain 'none';encrypted-media 'none';fullscreen 'none';geolocation 
                    'none';sync-xhr '...
Forms             : {}
Headers           : {[Feature-Policy, accelerometer 'none';autoplay 'none';camera 'none';display-capture 'none';document-domain 'none';encrypted-media 'none';fullscreen 'none';geolocation 
                    'none';sync-xhr 'none';usb 'none';xr-spatial-tracking 'none'], [Phpdebugbar-Id, X4147e4696619d815341e2f67cdc4e37c], [Pragma, no-cache], [Referrer-Policy, same-origin]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 218
```

I tried looking through the laravel logs at `/var/www/html/snipe-it/storage/logs/laravel.log` but I can't see anything special. 

I also tried enabling the debugger by adding `APP_DEBUG=false` in the `/var/www/html/snipe-it/.env` but I can't really see anything appear there when I launch the API request over PowerShell.

### Expected behavior

I would expect the user accounts to get created and a success message.

### Snipe-IT Version

v7.0.11 - build 14904 (master)

### Operating System

Ubuntu 22.04.4 LTS

### Web Server

Apache

### PHP Version

8.1 (I think)

### Operating System

Windows

### Error messages

```shell
As mentionned above, it seems like this is working fine in the "demo", at least the API test environment, which is a bit confusing.

Output of `php -m`


/var/www/html/snipe-it$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
```


### Additional context

This is a fully up-to-date SnipeIT installed on a Ubuntu 22.04.4 VM and it's installed using install.sh/git. The install has been working for 2-3 years and doesn't really have other issues as far as I know.
