### ISSUE TITLE
Docker Compose SSL Config

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#15346]
### Discussed in https://github.com/snipe/snipe-it/discussions/15337

<div type='discussions-op-text'>

<sup>Originally posted by **Masterain98** August 20, 2024</sup>
![image](https://github.com/user-attachments/assets/f2491653-49b5-40ef-ae9f-206eda681a79)

I'm receiving a URL error in the pre-flight page, showing `Uh oh! Snipe-IT thinks your URL is http://my-domain.com/setup, but your real URL is https://my-domain.com:80/setup Please update your APP_URL settings in your .env file`. If I ignore the error and continue to process, some form in the Snipe-it won't response.

Here is the docker compose file, I'm using Cloudflare Tunnel to connect the system to the Internet with SSL.

```
volumes:
  db_data:
  storage:

services:
  app:
    image: snipe/snipe-it:${APP_VERSION:-v6.4.1}
    restart: always
    volumes:
      - ./storage:/var/lib/snipeit
    env_file:
      - .env

  tunnel:
    container_name: Snipe-IT-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=
```

Followed some other issues, added `APP_TRUSTED_PROXIES=REMOTE_ADDR, SECURE_COOKIES=true` in the `.env` environment file

</div>
