### ISSUE TITLE
Kubernetes pod ignores APP_KEY in .env

### ISSUE THREAD

**Issue by icelava** [grokability/snipe-it#15384]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When I first tested Snipe-IT as raw source-code application on IIS, it was able to operate just fine with the configured .env file

```
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:=
APP_URL=http://localhost:30000
APP_TIMEZONE='Asia/Singapore'
APP_LOCALE='en-US'
MAX_RESULTS=500
```

However, on stepping up the sophistication to hosting on Kubernetes, there's an oddity with the container of snipe/snipe-it ignoring APP_KEY defined in the mounted .env file (from a secret). Other configuration parameters like database server and SMTP server still read ok. Ended up having to explicitly define extra env APP_KEY to container.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snipe-it-server
  namespace: snipe-it
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: snipe-it-server
  template:
    metadata:
      namespace: snipe-it
      labels:
        tier: snipe-it-server
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: snipe-it-pvc
        - name: php-ini
          configMap:
            name: snipe-it-php
        - name: secrets
          secret:
            secretName: snipe-it-secrets
      containers:
        - name: server
          image: snipe/snipe-it
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: snipe-it-secrets
                  key: APP_KEY
          volumeMounts:
            - name: storage
              mountPath: /var/lib/snipeit
            - name: php-ini
              mountPath: /etc/php/8.1/apache2/php.ini
              subPath: php.ini
              readOnly: true
            - name: secrets
              mountPath: /var/www/html/.env
              subPath: .env
              readOnly: true
```

### Reproduction steps

1. Use .env that worked with raw source-code (local) version. Edited for Kubernetes hosting environment.
2. Add .env as base64 secret in Kubernetes.
3. Define deployment container to mount .env file from secret volume.
...

### Expected behavior

Container to launch and Snipe-IT app use everything in mounted .env just like raw source-code version.

### Screenshots

Container launches and closes instead with

```
Please re-run this container with an environment variable $APP_KEY
An example APP_KEY you could use is: 
base64:=
```

### Snipe-IT Version

v7.0.11 build 15044 (g46ed07642)

### Operating System

Ubuntu

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows 11

### Browser

Google Chrome

### Version

127.0.6533.120

### Error messages

```shell
Not error per se but as above, web app launches and demands APP_KEY environment variable when it is already inside .env.
```
