### ISSUE TITLE
Server Error 500 when trying to create backup

### ISSUE THREAD

**Issue by sesa-emation** [grokability/snipe-it#15466]
### Debug mode

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Trying to evaluate Snipe-IT for our org I have CSV imported our assets thrice and deleted previous attempts. When trying to prune deleted data (because assets show up thrice on the user's account page and I assume it's the deleted ones) I get a server 500 error. Looking deeper into this I saw this is because before pruning the data, it attempts to create a backup first, which fails.

### Reproduction steps

1. In the UI, go to Admin -> Backups and click Generate Backup

### Expected behavior

A backup is generated

### Screenshots

![image](https://github.com/user-attachments/assets/84f7e510-106a-4aac-bbf7-d086f490a5b4)

### Snipe-IT Version

v7.0.11 build 15044 (g46ed07642)

### Operating System

Docker on openSUSE Tumbleweed

### Web Server

Apache (from Docker image behind Nginx reverse proxy)

### PHP Version

8.1.2-1ubuntu2.18

### Operating System

Windows 11

### Browser

Microsoft Edge

### Version

128.0.2739.42 (64-bit)

### Error messages

```shell
Spatie\DbDumper\DbDumper::setPort(): Argument #1 ($port) must be of type int, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 58
```

### Additional context

docker-compose.yaml
```yaml
services:
  snipe-it:
    image: snipe/snipe-it
    container_name: snipeit
    volumes:
      - /opt/docker/snipe-it/snipe-it:/var/lib/snipeit
    env_file: stack.env
    networks:
      snipe-it:
      mariadb:
    # to avoid "mysql connection refused" error, wait for database container 
    # to be started before starting this container
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - /opt/docker/snipe-it/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      mariadb:
    # configure a health check for this container so that other containers
    # can wait for it to be running
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

networks:
  snipe-it:
  mariadb:
```

stack.env
```env
MYSQL_ROOT_PASSWORD=*****
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=*****
MAIL_PORT_587_TCP_ADDR=smtp.office365.com
MAIL_PORT_587_TCP_PORT=587
MAIL_ENV_FROM_ADDR=*****
MAIL_ENV_FROM_NAME=*****
MAIL_ENV_ENCRYPTION=tls
MAIL_ENV_USERNAME=*****
MAIL_ENV_PASSWORD=*****
APP_ENV=production
APP_DEBUG=true
APP_KEY=*****
APP_URL=https://snipe-it.myorg.local
APP_TIMEZONE=Europe/Berlin
APP_LOCALE=de-DE
PHP_UPLOAD_LIMIT=100
APP_TRUSTED_PROXIES=nginx-proxy-manager
MYSQL_PORT_3306_TCP_ADDR=mariadb
ALLOW_DATA_PURGE=true
```
