### ISSUE TITLE
Mysql Connection refused - post upgrade - working prior

### ISSUE THREAD

**Issue by twojons** [grokability/snipe-it#17021]
In the middle of a docker upgrade from an old version, to a new version, in preparation to migrate our production instance, but running into a db connection error. Running Snipe-IT and the database in docker, with persistent storage, mapping env files, ports, etc. 

Old version (images):
mysql:5.6
snipe/snipe-it:v6.2.3
Docker version 28.1.1, build 4eba377

New version (images):
mysql:5.7
snipe/snipe-it:v8.1.3
Docker version 28.1.1, build 4eba377

Following the [steps](https://snipe-it.readme.io/docs/docker#updating-snipe-it-or-mysql) illustrated in the instructions. Built the new container, using the same volumes with a different name, as instructed. Was able to do the `docker compose pull` to upgrade both the database, and app, after both were up was able to run `php artisan migrate` from within the app container, which eventually reported successfully. 

![Image](https://github.com/user-attachments/assets/4a1854b5-e17a-4971-bed5-6e628e30efd8)

The error:
```
   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select exists (select 1 from information_schema.tables where table_schema = 'snipeit' and table_name = 'migrations' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED')) as `exists`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +41 vendor frames

  42  artisan:33
      Illuminate\Foundation\Console\Kernel::handle()


   INFO  Configuration cache cleared successfully.


   INFO  Configuration cached successfully.
```

I've tried to reproduce the issue, by connecting to the snipe-it container, and expecting to get the same MySQL error, _but did not_, while using the same credentials, found in the env file used by the snipe-it container. And running the sql statement, from the logs, completes successfully. 

![Image](https://github.com/user-attachments/assets/61e39cf4-da65-4230-98b4-a649fe7a435e)

I believe, because of the error, the application refuses to start. Although it looks like `apache2 is running`, yet I'm receiving a 404.

**Comment by snipe** [comment]
@uberbrady can you take a look?

**Comment by uberbrady** [comment]
From within the Snipe-IT container, can you run `php artisan db`? And then, do you get a valid MySQL prompt? I don't actually remember if we give you the `mysql` command-line tool or not in our container, so that _might_ not work. You might need to install it, if so.

If you can connect from your Snipe-IT container to the DB, then at least your basic networking is working.

Also, since it seems like you _can_ run migrations, I would expect that _something_ is working here - I'm just not sure where it might be broken.

I'm not 100% convinced that the error you saw was legit - it's possible that your Snipe-IT container came up _before_ your database did - and the Snipe-IT container _does_ try to run migrations for you before it launches the app. But it can't if the DB isn't up.

You might also want to check the Apache logs on the container itself to see if the error or access logs give you anything to go on.

**Comment by twojons** [comment]
Thanks @uberbrady I was able to run the `php artisan db` and it did drop me a sql prompt:
```shell
root@f1dd3f5c6637:/var/www/html# php artisan db
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1308
Server version: 5.7.44 MySQL Community Server (GPL)

Copyright (c) 2000, 2025, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

So yes, I'd agree, networking between containers is working properly. 

As for launch order, we have a `depends_on` statement in the docker-compose, so that snipe-it would wait for the db container to at least be started; I may add a health check, to wait for the db to be up & healthy. 

Here's the compose with a few options redacted for security. 
```yaml
services:

  snipe-mysql:
    container_name: snipe-mysql
    restart: unless-stopped
    image: mysql:5.7
    env_file:
      - <redacted>
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./export:/export
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

  snipe-it:
    image: snipe/snipe-it:v8.1.3
    restart: unless-stopped
    volumes:
      - ./data/storage:/var/www/html/storage
      - ./data/data:/var/lib/snipeit/data
      - ./data/keys:/var/lib/snipeit/keys
    env_file:
      - <redacted>
    ports:
      - "80:80"
      - "8080:80"
    depends_on:
      - snipe-mysql
```

I'll dig into the apache logs within snipe-it container to see if we're at least getting some entries in the access log, and maybe something in the error log; will report back.
