### ISSUE TITLE
Custom CSS for asset labels with Brother PT-700

### ISSUE THREAD

**Issue by tarrenj** [grokability/snipe-it#7657]
**Server:**
 - 4.8
 - OS: Official Docker containers on Debian

Heyo! I'm posting this here since I looked around to see if anyone had done this yet before doing it myself.

The Brother PT-700 label printer has a maximum width of .94", and doesn't have enough resolution to print both the QRCode and C39 barcode for my [reader](https://www.amazon.com/NADAMOO-Handheld-Automatic-Datamatrix-Scanning/dp/B07LG4TBVZ/ref=sr_1_17?keywords=nadamoo+barcode+scanner&qid=1575992211&sr=8-17) to understand at that size.  I've used the Custom CSS text box under Branding to tweak how they're generated (It's ugly, but it works so :man_shrugging:):

```css
div.qr_img {
    width: 0.795in;
    height: 0.795in;
    float: left;
    display: inline-block;
    padding-right: .04in;
    padding-top: .02in;
  }
  img.qr_img {
    width: 100%;
    height: 100%;
  }
  img.barcode {
    width: 100%;
    display: block;
    margin-left: auto;
    float: left;
  }

 .qr_text {
    width: 60%;
    height: 0.42in;
    padding-right: 3px;
    font-family: arial, helvetica, sans-serif;
    overflow: hidden !important;
    display: inline-block;
    white-space: nowrap;
    text-align: left;
  }

  div.barcode_container {
      float: left;
      width: 65%;
      display: inline;
      height: 20px;
      overflow: hidden !important;
  }
```

The printer leaves too much on either side of each label for our liking, so we printed them in strips of 12 and cut them manually, stacking all of the strips on top of each other worked nicely. There were some issues with the margins too, but these settings worked that out:
![image](https://user-images.githubusercontent.com/3710484/70668380-72a3a280-1c41-11ea-9750-39866c3c678b.png)

Now the labels look like this (Please forgive my Pinta skills...):
![image](https://user-images.githubusercontent.com/3710484/70668773-7ab01200-1c42-11ea-9e15-6f2f3023e887.png)

This is as small as I could get the labels and still have our reader able to scan them all easily enough. I needed space for up to 30 chars in the `qr_text` field.

I hope these settings help someone else! Let me know if they do :smile:

**Comment by tarrenj** [comment]
Closing this issue since I just created it to document the settings that work best here.

**Comment by viclou** [comment]
Another user has made a few tweaks, so if you find this isn't quite right, try:

```css
div.qr_img {
    width: 1.04in;
    height: 1.04in;
    float: left;
    display: inline-block;
    padding-right: .04in;
    padding-top: .02in;
  }
  img.qr_img {
    width: 100%;
    height: 100%;
  }
  img.barcode {
    width: 100%;
    display: block;
    margin-left: auto;
    float: left;
  }

 .qr_text {
    width: 60%;
    height: 0.50in;
    padding-right: 3px;
    font-family: arial, helvetica, sans-serif;
    overflow: hidden !important;
    display: inline-block;
    white-space: nowrap;
    text-align: left;
  }

  div.barcode_container {
      float: left;
      width: 60%;
      display: inline;
      height: 40px;
      overflow: hidden !important;
  }
```

![image](https://user-images.githubusercontent.com/20525448/123196179-513e8c00-d45e-11eb-8eef-dff95c289b00.png)
