### ISSUE TITLE
Docker: outdated PHP?

### ISSUE THREAD

**Issue by Smankusors** [grokability/snipe-it#8314]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I read the Dockerfile that you guys are still using PHP 7.1
https://github.com/snipe/snipe-it/blob/e0644dbbf6b5601b6712ca16877b481799e9652c/Dockerfile#L9-L18
According to the [PHP documentation](https://www.php.net/supported-versions.php), this version is no longer supported, so I recommend to upgrade PHP to PHP 7.4.

Another reason? Yes, I can't run PHP 7.1 because my DB are MySQL 8.0. And here's the problem,
```
Illuminate\Database\QueryException thrown with message "SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = db_snipe and table_name = users)"

Previous exceptions
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (2054)
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (2054)
PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] (0)
```
I believe this is similiar to https://github.com/YOURLS/docker-yourls/issues/50.

**To Reproduce**
Here just use this docker compose to reproduce
```
version: '3'

services:
  snipe-it:
    image: snipe/snipe-it:v4.9.4
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - APP_DEBUG=true
      - APP_KEY=base64:R4yKHxalPFHv6jPRer3tNBnG3Nug2FKxvPOPyPJTzrI=
    ports:
      - "192.168.9.35:3051:80"
    volumes:
      - ./data:/var/lib/snipeit
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=snipeit
```

**Expected behavior**
Runs normally

**Screenshots**
I think...  this is already clear enough.

**Tested Docker image tags**
* latest (DIGEST:sha256:49ac7d27637d0866d1e5cef5aceb92e2e4f19690133db5213e8c5b5ad76cd0df)
* develop (DIGEST:sha256:c6ec9e85a75b9660d622e9c52dc898bd0c4d7e74090236b82d0b0fc1790165c3)
* snipe/snipe-it:v4.9.4
* snipe/snipe-it:v5.0.0-beta-2

**Additional context**
I could do PR if you want to upgrade the image to PHP 7.4 btw. Also I see that v5 is already upgraded to PHP 7.2, but it's still same as issue I mentioned. And it's fixed after I upgraded it to PHP 7.4.

Eh wait, I read #6701 and it seems I run out of luck run this with MySQL 8, even if this fixed?
