### ISSUE TITLE
Unable to execute backup on docker

### ISSUE THREAD

**Issue by Quantum-Sicarius** [grokability/snipe-it#8652]
**Describe the bug**
Error 500 on creating a backup via GUI or CMD

**Expected behaviour**
Backup created

**Server (please complete the following information):**
 - Snipe-IT Version:  v5.0.4 - build 5452 (master)
 - OS: docker
 - Web Server: Laravel 6.18.10  
 - PHP Version 7.2.24-0ubuntu0.18.04.7 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 82

**Error Messages**
```
root@f39eb9b1612e:/var/www/html# php artisan snipeit:backup
Starting backup...

In DbDumper.php line 120:
                                                                                                                                                                                                            
  Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given, called in /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php on line 51

```

**docker-compose**
```
  snipe:
   image: snipe/snipe-it
   container_name: snipe-it
   environment:
     DB_CONNECTION: mysql
     DB_HOST: 10.0.0.5
     DB_DATABASE: snipe
     DB_USERNAME: root
     DB_PASSWORD: "pass"
```

**Additional context**
- Fresh
- Docker
- Indicate whether or not you've manually edited any data directly in the database - No
- Everything works normally execept executing a backup
