### ISSUE TITLE
Docker volume for uploads is an ID

### ISSUE THREAD

**Issue by mrenbe** [grokability/snipe-it#8780]
Hello,

I created a docker compose that works fine. However when I upload a document in Snipe-IT I can see in the link an ID. This ID is the ID of the volume docker created. Inside /var/lib/docker/volumes I can see the both volumes I created in the docker-compose but there is a 3rd volume. Inside this 3rd volume there are the 2 directories for uploads.

I dropped the container and I recreated from my docker-compose then the ID change. I restore the content of the MySQL database and all data are there. But If I clic on a document the link is not working anymore because of a wrong ID.

Is there a possibility to store the uploads in a "known" directory?

**Comment by uberbrady** [comment]
I don't know much about docker-compose, but I do know that our Dockerfile expects to find a volume mounted on `/var/lib/snipeit`. If you didn't explicitly mention a volume mount there, I suspect that Docker is just generating a random ID for the volume and mounting it there. You can probably explicitly reference that ID and that you want it to mount there, and then your images should come back.

We *try* (perhaps not always succeed) to follow the Docker ethos of making our containers be 'disposable' - hence the volume reference in the Dockerfile. Your uploads *should* persist even if you throw away the container and regenerate it.

If you're seeing something in your broken-image URL's that actually *mentions* the weird random ID of your volume, that seems weird. Snipe-IT definitely doesn't do that. I just hope that Docker isn't doing something weird here.

If you can share any docker-compose files or environment files (with sensitive data redacted, of course) maybe I can help you figure out what's going wrong.

**Comment by mrenbe** [comment]
Here is the docker-compose.yml

```
version: "3.5"

volumes:
  snipe_db_data:
  snipe_it_data:

services:
  mysql:
    image: mysql:5.7
    container_name: snipe_mysql
    restart: always
    volumes:
      - snipe_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=mypassagain
      - MYSQL_DATABASE=snipe
    ports:
      - "3306:3306"
  snipeit:
    image: snipe/snipe-it:latest
    container_name: snipeit
    restart: always
    volumes:
      - snipe_it_data:/var/www/html
    depends_on:
      - mysql
    environment:
      - APP_URL=asset.localdomain.com
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:hDA2W2DmVefefefevdvmfimfiEdr3rt3j
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=mypass
      - PGID=1000
      - PUID=1000
      - SNIPEIT_APP_NAME="Assets Management"
      - SNIPEIT_APP_DIR=/var/www/html
      - SNIPEIT_TARBALL=/tmp/snipeit_tar/
    ports:
      - "80:80"
```

**Comment by uberbrady** [comment]
I think the piece that you wanted was this:

```
services:
  snipeit:
    volumes:
      - snipe_it_data:/var/lib/snipeit
```

I suspect your `snipe_it_data` volume is empty? Or does it have a full Snipe-IT installation on it?
