### ISSUE TITLE
Change Alternate row color in dark mode

### ISSUE THREAD

**Issue by LukeHislop-SSRG** [grokability/snipe-it#9763]
#### Need to change the alternate row colour in dark mode.

I can't find a setting or even a css example that allows the changing of the alternate row colour

-----

#### The current colour scheme in any of the dark modes is very jarring

There needs to be a more subtle colour change for alternate rows in the latest version
![Snipe-IT_AssetView](https://user-images.githubusercontent.com/85907148/123710935-ec968d80-d8b2-11eb-84df-e8c078f3dd93.png)

This is not a bug a such it is just an ugly GUI
I cannot find any reference to changing the alternate row colour

This issue appeared only recently in the hosted version
 Version v5.1.6 - build 6109 (develop)

**Comment by snipe** [comment]
In Admin > Settings, in your custom CSS field, add:

```css
.table-striped>tbody>tr:nth-of-type(2n) {
background-color: var(--back-sub);
color: var(--header);
}
```
